### PR TITLE
Teach Loohp-Limbo how to login clients connecting via floodgate

### LINKED ISSUE #54: "Please connect from the proxy" error when connecting to loohp-limbo server via velocity proxy with Geyser and Floodgate plugins
This is another issue I've run into while connecting from a bedrock client (1.19.30) via Velocity proxy (3.1.2-SNAPSHOT-184) configured with the Geyser (Build 1195) and Floodgate (Build 73) plugins.  This is with the latest Loohp Limbo server as of the time of writing.

The root cause is that the Bungeecord login (velocity config option `player-info-forwarding-mode = "legacy"`) seems to
sometimes send a Floodgate key and sometimes it doesn't.  I haven't been able to root cause why that is, but the consequence is that the `case LOGIN:` handler in `ClientConnection.java` which pulls the client IP addr from `data[2]` sometimes gets the ip addr, and sometimes gets the Floodgate cipher.

I spent a few hours digging around in the Velocity, Geyser, and Floodgate sources, but I'm not a Java expert and failed to find where the bungeecord-ified login message is constructed.  In comparison, the Loohp Limbo login handler is super clear and straightforward, so I've just handled the "optional" floodgate cipher attribute being sent or not-sent there.

PR coming momentarily which fixes the problem for me.

### PR DESCRIPTION
**Pull request by tadhunt**
This PR fixes #54.

Note that in the following LOGIN traces, PII has been removed, but the traces are otherwise unaltered.  These traces are from the code in the PR, so you should be able to reproduce.  I am not sure if this matters, but in the case where the Floodgate cipher is **not** sent, the client and server are on my LAN, but in the case where it **is** sent, the client is on my LAN and the server in in the cloud.  Velocity, Geyser, Floodgate and Loop Limbo configurations are identical in both locations, and software versions are also identical.

Client is the same iPad in both cases, running Minecraft 1.19.30.

_LOGIN from client where the Floodgate cipher is not sent_:
```
[14:45:08 Info] Loaded world minecraft:world!
[14:45:08 Info] Limbo server listening on /0.0.0.0:30000
[14:46:02 Info] 0: H.H.H.H
[14:46:02 Info] 1: C.C.C.C
[14:46:02 Info] 2: 000000000000000000090XXXXXXXXXXXX
[14:46:02 Info] 3: [{"name":"textures","value":"","signature":""},{"name":"textures","value":"XXX","signature":"XXX"}]
[14:46:02 Info] Host: H.H.H.H
[14:46:02 Info] Floodgate: 
[14:46:02 Info] clientIp: C.C.C.C
[14:46:02 Info] bungee: 00000000000000000009XXXXXXXXXXXX
[14:46:02 Info] skinData: [{"name":"textures","value":"","signature":""},{"name":"textures","value":"XXX","signature":"XXX"}]
[14:46:03 Info] [/192.168.50.165:49769|*XXX(00000000-0000-0000-0009-XXX)] <-> Player had connected to the Limbo server!
```
Note that the `Floodgate:` line shows no content, and there are only 4 items in the `data` array.

*Login from client where the Floodgate cipher is sent*:
```
[21:37:08 Info] Limbo server listening on /0.0.0.0:30000
[21:37:15 Info] 0: H.H.H.H
[21:37:15 Info] 1: ^Floodgate^>XXXXXXXXXXXXXXXX+XXXXXXXXXXXXXXXXXXXXXXXX
[21:37:15 Info] 2: C.C.C.C
[21:37:15 Info] 3: 00000000000000000009XXXXXXXXXXXX
[21:37:15 Info] 4: [{"name":"textures","value":"XXX","signature":"XXX"}]
[21:37:15 Info] Host: H.H.H.H
[21:37:15 Info] Floodgate: ^Floodgate^>XXXXXXXXXXXXXXXX+XXXXXXXXXXXXXXXXXXXXXXXX
[21:37:15 Info] clientIp: C.C.C.C
[21:37:15 Info] bungee: 00000000000000000009XXXXXXXXXXXX
[21:37:15 Info] skinData: [{"name":"textures","value":"XXX","signature":"XXX"}]
[21:37:16 Info] [C.C.C.C:52168|*XXXX(00000000-0000-0000-0009-XXXXXXXXXXXX)] <-> Player had connected to the Limbo server!
```
Note that the `Floodgate:` line is not empty, and there are 5 items in the `data` array.

The old code always assumed `data[1]` contained the bungeecord provided UUID, but as we can see from the two traces, sometimes it's at `data[1]` and sometimes it's at `data[2]`

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -11,4 +11,13 @@ target/
...
+.settings/ 
+
+Loohp-Limbo.jar
+Loohp-Limbo-*.jar
+internal_data/
+logs/
+permission.yml
+plugins/
+server.properties
+
```
Comment (LOOHP) [inline .gitignore]: Can you remove the `.gitignore` changes?

File: src/main/java/com/loohp/limbo/network/ClientConnection.java [hunk 2]
```diff
@@ -362,15 +364,57 @@ public void run() {
...
+                                    }
+                                }
 
-                                bungeeUUID = UUID.fromString(data[2].replaceFirst("([0-9a-fA-F]{8})([0-9a-fA-F]{4})([0-9a-fA-F]{4})([0-9a-fA-F]{4})([0-9a-fA-F]+)", "$1-$2-$3-$4-$5"));
-                                inetAddress = InetAddress.getByName(ip);
+                                Limbo.getInstance().getConsole().sendMessage("Host: " + host);
+                                Limbo.getInstance().getConsole().sendMessage("Floodgate: " + floodgate);
+                                Limbo.getInstance().getConsole().sendMessage("clientIp: " + clientIp);
+                                Limbo.getInstance().getConsole().sendMessage("bungee: " + bungee);
+                                Limbo.getInstance().getConsole().sendMessage("skinData: " + skinData);
```
Comment (LOOHP) [inline src/main/java/com/loohp/limbo/network/ClientConnection.java:409]: Can you make these (and the other) debug messages togglable in `server.properties`?

File: src/main/java/com/loohp/limbo/network/ClientConnection.java [hunk 3]
```diff
@@ -390,6 +434,10 @@ public void run() {
                                     break;
                                 }
                             } catch (Exception e) {
+                                StringWriter sw = new StringWriter();
+                                PrintWriter pw = new PrintWriter(sw);
+                                e.printStackTrace(pw);
+                                Limbo.getInstance().getConsole().sendMessage(sw.toString());
```
Comment (LOOHP) [inline src/main/java/com/loohp/limbo/network/ClientConnection.java:440]: I think this can also be only showed if the debug option is enabled

File: src/main/java/com/loohp/limbo/network/ClientConnection.java [hunk 4]
```diff
@@ -362,15 +364,57 @@ public void run() {
...
                                 String[] data = bungeeForwarding.split("\\x00");
-                                //String host = data[0];
-                                String ip = data[1];
+                                String host = "";
+                                String floodgate = "";
+                                String clientIp = "";
+                                String bungee = "";
+                                String skinData = "";
+                                int state = 0;
+                                for(int i = 0; i < data.length; i++) {
```
Comment (LOOHP) [inline src/main/java/com/loohp/limbo/network/ClientConnection.java:373]: Missing a space after `for`

**Review by LOOHP — CHANGES_REQUESTED** [review]

File: .gitignore (hunk 1 above)
Comment (tadhunt) [reply .gitignore]: fixed

File: src/main/java/com/loohp/limbo/network/ClientConnection.java (hunk 2 above)
Comment (tadhunt) [reply src/main/java/com/loohp/limbo/network/ClientConnection.java]: I conditionalized this on the `server.properties` `reduced-debug-info=true` setting, I wasn't sure if that's what you meant or if I should add a new debug flag?

File: src/main/java/com/loohp/limbo/network/ClientConnection.java (hunk 3 above)
Comment (tadhunt) [reply src/main/java/com/loohp/limbo/network/ClientConnection.java]: I also conditionalized this on the `server.properties` `reduced-debug-info=true` flag, happy to change it if that's not what you meant.

File: src/main/java/com/loohp/limbo/network/ClientConnection.java (hunk 4 above)
Comment (tadhunt) [reply src/main/java/com/loohp/limbo/network/ClientConnection.java]: fixed

File: src/main/java/com/loohp/limbo/network/ClientConnection.java [hunk 5]
```diff
@@ -360,17 +362,68 @@ public void run() {
...
+                                String clientIp = "";
+                                String bungee = "";
+                                String skinData = "";
+                                int state = 0;
+                                for (int i = 0; i < data.length; i++) {
+                                    if (!properties.isReducedDebugInfo()) {
+                                        Limbo.getInstance().getConsole().sendMessage(String.valueOf(i) + ": " + data[i]);
+                                    }
+
+                                    switch(state) {
```
Comment (LOOHP) [inline src/main/java/com/loohp/limbo/network/ClientConnection.java:379]: Also a space here after `switch`

File: src/main/java/com/loohp/limbo/network/ClientConnection.java [hunk 6]
```diff
@@ -360,17 +362,68 @@ public void run() {
...
+                                    default:
+                                        Limbo.getInstance().getConsole().sendMessage(String.valueOf(i) + ": ignore data: State: " + String.valueOf(state));
+                                        break;
+                                    case 0:
+                                        host = data[i];
+                                        state = 1;
+                                        break;
+                                    case 1:
+                                        if(data[i].startsWith("^Floodgate^")) {
```
Comment (LOOHP) [inline src/main/java/com/loohp/limbo/network/ClientConnection.java:388]: Also a space here after `if`

File: src/main/java/com/loohp/limbo/network/ClientConnection.java (hunk 3 above)
Comment (LOOHP) [reply src/main/java/com/loohp/limbo/network/ClientConnection.java]: It's ok! Thanks!

File: src/main/java/com/loohp/limbo/network/ClientConnection.java (hunk 2 above)
Comment (LOOHP) [reply src/main/java/com/loohp/limbo/network/ClientConnection.java]: It's ok like this! Thanks!

**Review by LOOHP — CHANGES_REQUESTED** [review]

File: src/main/java/com/loohp/limbo/network/ClientConnection.java (hunk 5 above)
Comment (tadhunt) [reply src/main/java/com/loohp/limbo/network/ClientConnection.java]: whoops, I missed this one, thanks, fixed!

File: src/main/java/com/loohp/limbo/network/ClientConnection.java (hunk 6 above)
Comment (tadhunt) [reply src/main/java/com/loohp/limbo/network/ClientConnection.java]: whoops, I missed this one, thanks, fixed!
